
apiVersion: apps/v1   # app-related things (Deployments, StatefulSets, etc.)
kind: Deployment
metadata:
  name: internal-app
  namespace: cloud-engineering
spec:
  replicas: 0
  selector:
    matchLabels:
      app: internal-app
  template:
    metadata:
      labels:
        app: internal-app
    spec:
      serviceAccountName: cloud-engineers
      containers:
      - name: app-container
        image: nginx
        ports:
        - containerPort: 80  