apiVersion: v1
kind: Pod
metadata:
  name: app1-pod-1
  namespace: app1-dev
  labels:
    app: app1
    env: dev

spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80


# In first YAML (Namespace), you are creating the namespace itself.

# In second YAML (Pod), you are using an existing namespace.

