
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:      # specifications/ contents for replicationscotroller
  replicas: 3   
  selector:   # label selection for replicationcontroller
    app: nginx
  template:   # pod template
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:    # spec for containers
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


 # akms - api version, kind, metadata, specifications       